# Generated by Django 3.2.8 on 2022-04-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='01G0CXQKXM3ZEEDFES5BHBFZKK', max_length=26, verbose_name='ユーザーID'),
        ),
    ]
