# Generated by Django 4.0.4 on 2022-04-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='01G0FE79VZPWGD7NT2BAPDXMN5', max_length=26, verbose_name='ユーザーID'),
        ),
    ]
