# Generated by Django 3.2.8 on 2022-04-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='01G04YHHWC7MTV34T1S093828E', max_length=26, verbose_name='ユーザーID'),
        ),
    ]
