# Generated by Django 3.2.8 on 2022-02-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='icon',
            field=models.ImageField(blank=True, default='profile/icon/default.jpg', upload_to='profile/icon/', verbose_name='アイコン'),
        ),
    ]
