# Generated by Django 3.2.8 on 2022-04-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='01G0510K0HG9THC4SHMJCC411E', max_length=26, verbose_name='ユーザーID'),
        ),
    ]
