# Generated by Django 3.2.8 on 2022-03-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ユーザー名')),
                ('room', models.CharField(max_length=255, verbose_name='トークルーム')),
                ('text', models.CharField(blank=True, max_length=144, verbose_name='テキストの入力')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='送られた時間')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=255, verbose_name='トークルーム')),
            ],
        ),
    ]
