# Generated by Django 3.2.8 on 2022-04-11 18:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='meta',
            field=models.ManyToManyField(related_name='add_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='meta',
            field=models.ManyToManyField(to='accounts.Tag'),
        ),
    ]
