# Generated by Django 3.2.8 on 2022-04-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='room',
            field=models.CharField(max_length=10, verbose_name='トークルーム'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room',
            field=models.CharField(max_length=10, verbose_name='トークルーム'),
        ),
    ]
